#!/usr/bin/env node
// Extract every {en, zh} text pair from data/skills.js and data/anthology.js
// into data/locales/{en,zh}.js keyed by the English source text (msgid design).
// New language = add one data/locales/<code>.js file with the same shape.
// Re-run after editing any data file: node scripts/sync_locales.mjs
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "data", "locales");
fs.mkdirSync(outDir, { recursive: true });

function loadData(file, globalName) {
  const code = fs.readFileSync(path.join(root, file), "utf8");
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(code, sandbox);
  return sandbox.window[globalName];
}

const data = {
  skills: loadData("data/skills.js", "AMHS_DATA"),
  anthology: loadData("data/anthology.js", "AMHS_ANTHOLOGY"),
};

const pairs = [];
function walk(node, trail) {
  if (Array.isArray(node)) { node.forEach((v, i) => walk(v, `${trail}[${i}]`)); return; }
  if (node && typeof node === "object") {
    const keys = Object.keys(node);
    if (keys.length === 2 && keys.includes("en") && keys.includes("zh") &&
        typeof node.en === "string" && typeof node.zh === "string") {
      pairs.push({ en: node.en, zh: node.zh, trail });
      return;
    }
    for (const k of keys) walk(node[k], `${trail}.${k}`);
  }
}
for (const [k, v] of Object.entries(data)) walk(v, k);

// dedupe by English text (keep first zh, record duplicate trails for reporting)
const seen = new Map();
const dups = [];
for (const p of pairs) {
  if (seen.has(p.en)) dups.push({ en: p.en, trail: p.trail, first: seen.get(p.en) });
  else seen.set(p.en, p.trail);
}

const en = {};
const zh = {};
for (const p of pairs) { en[p.en] = p.en; zh[p.en] = p.zh; }

const header = `// Auto-generated by scripts/sync_locales.mjs — do not edit by hand.\n// Key = English source text (msgid). Run the script again after editing data files.\n`;
fs.writeFileSync(path.join(outDir, "en.js"), `${header}window.AMHS_LOCALES = window.AMHS_LOCALES || {};\nwindow.AMHS_LOCALES.en = ${JSON.stringify(en, null, 2)};\n`);
fs.writeFileSync(path.join(outDir, "zh.js"), `${header}window.AMHS_LOCALES = window.AMHS_LOCALES || {};\nwindow.AMHS_LOCALES.zh = ${JSON.stringify(zh, null, 2)};\n`);

console.log(`pairs: ${pairs.length}  unique-en: ${seen.size}  duplicate-msgids: ${dups.length}`);
if (dups.length) {
  console.log("duplicate English texts (first trail kept):");
  for (const d of dups.slice(0, 15)) console.log(`  ${JSON.stringify(d.en).slice(0, 60)}  ${d.trail} (first: ${d.first})`);
}
